# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='nome')),
            ],
        ),
    ]
