# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20151220_1859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Participant',
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participante do amigo secreto', 'verbose_name_plural': 'Participantes do amigo secreto'},
        ),
    ]
